# Generated by Django 4.2.7 on 2023-11-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0011_empleados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='id_habitacion',
        ),
        migrations.DeleteModel(
            name='Reserva_Huesped',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
