# Generated by Django 4.2.7 on 2023-11-21 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesTourApp', '0012_remove_reservas_id_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('observation', models.TextField(blank=True, max_length=500)),
                ('cost', models.IntegerField()),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesTourApp.hoteles')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesTourApp.habitacion')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
