# Generated by Django 4.2.7 on 2023-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0014_reserva_huesped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
