# Generated by Django 4.2.7 on 2023-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0015_alter_reservas_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cost',
            field=models.TextField(),
        ),
    ]
