# Generated by Django 4.2.7 on 2024-02-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourApp', '0017_alter_reservas_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva_Huesped',
            new_name='ReservaHuesped',
        ),
        migrations.RenameModel(
            old_name='Tipo_Habitacion',
            new_name='TipoHabitacion',
        ),
        migrations.AlterModelOptions(
            name='reservahuesped',
            options={'verbose_name_plural': 'ReservaHuespedes'},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'verbose_name_plural': 'TipoHabitacion'},
        ),
    ]
