# Generated by Django 4.2.5 on 2023-09-30 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_hora_checkin',
            new_name='checkin_datetime',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_hora_checkout',
            new_name='checkout_datetime',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observation',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reserva',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
