# Generated by Django 4.2.7 on 2023-11-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesTourWeb', '0002_rename_fecha_hora_checkin_reserva_checkin_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
